import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
 
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [dollarsPerMonth, setDollarsPerMonth] = useState(0)
  const [interestRate, setInterestRate] = useState(0)
  const [yearsInvested, setYearsInvested] = useState(0)
  const [lowerAge, setLowerAge] = useState(0)
  const [upperAge, setUpperAge] = useState(0)
  const [finalAmount, setFinalAmount] = useState(0)

  useEffect(() => {
    setYearsInvested(upperAge - lowerAge)

    // Calculate final amount
    setFinalAmount(() => (
      yearsInvested * interestRate
    ))
  }, [upperAge, lowerAge, dollarsPerMonth, interestRate, yearsInvested])

  const amountPerYear = []
  for (let i = 0; i < 20; i++){
    console.log('dollars', dollarsPerMonth, 'amount:', amountPerYear, 'interest', interestRate, 'i: ', i)

    
    amountPerYear.push(dollarsPerMonth * 12 + (amountPerYear.length > 0 && amountPerYear[i - 1] * (interestRate+1)) )
    console.log(amountPerYear)
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Investment Calculator</h1>
          <div>
            <label>
              Amount invested every month: 
              <input  
                onChange={(e) => {
                  setDollarsPerMonth(e.target.value)
                }}
              />
            </label>
            <div>{dollarsPerMonth}</div>
          </div>
          <div>
            <label>
              Interest rate (%):
              <input  
                onChange={(e) => {
                  setInterestRate(e.target.value / 100)
                }}
              />
            </label>
            <div>{interestRate}</div>
          </div>
          <div>
            <label>
              Age range invested: from 
              <input  
                onChange={(e) => {
                  setLowerAge(e.target.value)
                  setYearsInvested(upperAge - lowerAge)
                }}
              />
              to 
              <input  
                onChange={(e) => {
                  setUpperAge(e.target.value)
                }}
              />
            </label>
            <div>{yearsInvested} years of investing</div>
          </div>
          <div>
            Amount of money at end: {finalAmount}
          </div>
          <div>
            Amount per year: {
              amountPerYear.map((value, index) => {
                return(
                  <>
                    <div>
                      Year {index + 1}: {value},
                    </div>
                  </>
                )
              })
            }
          </div>
        </div>
      </main>
    </>
  )
}
